name: update-market-data

on:
  schedule:
    # 03:05 UTC → 05:05 Europe/Madrid in winter, 04:05 in summer
    - cron: '5 3 * * *'
  workflow_dispatch:        # allow manual button

permissions:
  contents: write           # elevate built‑in GITHUB_TOKEN

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PUSH_TOKEN || secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --quiet yfinance pandas

      - name: Update CSVs
        run: python scripts/update_assets.py

      - name: Commit & push (only if data changed)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A data

          # Exit early if nothing changed
          if git diff --quiet; then
            echo "Nothing new to commit"
            exit 0
          fi

          git add data/*.csv
          git commit -m "chore(data): market close $(date -u +'%Y-%m-%d')"
          git push
